// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/brunomvsouza/warren/codec (interfaces: Codec,HeaderCodec)
//
// Generated by this command:
//
//	mockgen -destination codec.go -package amqpmock github.com/brunomvsouza/warren/codec Codec,HeaderCodec
//

// Package amqpmock is a generated GoMock package.
package amqpmock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCodec is a mock of Codec interface.
type MockCodec struct {
	ctrl     *gomock.Controller
	recorder *MockCodecMockRecorder
	isgomock struct{}
}

// MockCodecMockRecorder is the mock recorder for MockCodec.
type MockCodecMockRecorder struct {
	mock *MockCodec
}

// NewMockCodec creates a new mock instance.
func NewMockCodec(ctrl *gomock.Controller) *MockCodec {
	mock := &MockCodec{ctrl: ctrl}
	mock.recorder = &MockCodecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodec) EXPECT() *MockCodecMockRecorder {
	return m.recorder
}

// ContentType mocks base method.
func (m *MockCodec) ContentType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContentType")
	ret0, _ := ret[0].(string)
	return ret0
}

// ContentType indicates an expected call of ContentType.
func (mr *MockCodecMockRecorder) ContentType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContentType", reflect.TypeOf((*MockCodec)(nil).ContentType))
}

// Decode mocks base method.
func (m *MockCodec) Decode(data []byte, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", data, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockCodecMockRecorder) Decode(data, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockCodec)(nil).Decode), data, v)
}

// Encode mocks base method.
func (m *MockCodec) Encode(v any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", v)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockCodecMockRecorder) Encode(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockCodec)(nil).Encode), v)
}

// MockHeaderCodec is a mock of HeaderCodec interface.
type MockHeaderCodec struct {
	ctrl     *gomock.Controller
	recorder *MockHeaderCodecMockRecorder
	isgomock struct{}
}

// MockHeaderCodecMockRecorder is the mock recorder for MockHeaderCodec.
type MockHeaderCodecMockRecorder struct {
	mock *MockHeaderCodec
}

// NewMockHeaderCodec creates a new mock instance.
func NewMockHeaderCodec(ctrl *gomock.Controller) *MockHeaderCodec {
	mock := &MockHeaderCodec{ctrl: ctrl}
	mock.recorder = &MockHeaderCodecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHeaderCodec) EXPECT() *MockHeaderCodecMockRecorder {
	return m.recorder
}

// ContentType mocks base method.
func (m *MockHeaderCodec) ContentType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContentType")
	ret0, _ := ret[0].(string)
	return ret0
}

// ContentType indicates an expected call of ContentType.
func (mr *MockHeaderCodecMockRecorder) ContentType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContentType", reflect.TypeOf((*MockHeaderCodec)(nil).ContentType))
}

// Decode mocks base method.
func (m *MockHeaderCodec) Decode(data []byte, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", data, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockHeaderCodecMockRecorder) Decode(data, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockHeaderCodec)(nil).Decode), data, v)
}

// DecodeWithHeaders mocks base method.
func (m *MockHeaderCodec) DecodeWithHeaders(body []byte, headers map[string]any, contentType string, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeWithHeaders", body, headers, contentType, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecodeWithHeaders indicates an expected call of DecodeWithHeaders.
func (mr *MockHeaderCodecMockRecorder) DecodeWithHeaders(body, headers, contentType, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeWithHeaders", reflect.TypeOf((*MockHeaderCodec)(nil).DecodeWithHeaders), body, headers, contentType, v)
}

// Encode mocks base method.
func (m *MockHeaderCodec) Encode(v any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", v)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockHeaderCodecMockRecorder) Encode(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockHeaderCodec)(nil).Encode), v)
}

// EncodeWithHeaders mocks base method.
func (m *MockHeaderCodec) EncodeWithHeaders(v any) ([]byte, map[string]any, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodeWithHeaders", v)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(map[string]any)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// EncodeWithHeaders indicates an expected call of EncodeWithHeaders.
func (mr *MockHeaderCodecMockRecorder) EncodeWithHeaders(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodeWithHeaders", reflect.TypeOf((*MockHeaderCodec)(nil).EncodeWithHeaders), v)
}
