// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/brunomvsouza/warren/metrics (interfaces: ClientMetrics,PublisherMetrics,ConsumerMetrics)
//
// Generated by this command:
//
//	mockgen -destination metrics.go -package amqpmock github.com/brunomvsouza/warren/metrics ClientMetrics,PublisherMetrics,ConsumerMetrics
//

// Package amqpmock is a generated GoMock package.
package amqpmock

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockClientMetrics is a mock of ClientMetrics interface.
type MockClientMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockClientMetricsMockRecorder
	isgomock struct{}
}

// MockClientMetricsMockRecorder is the mock recorder for MockClientMetrics.
type MockClientMetricsMockRecorder struct {
	mock *MockClientMetrics
}

// NewMockClientMetrics creates a new mock instance.
func NewMockClientMetrics(ctrl *gomock.Controller) *MockClientMetrics {
	mock := &MockClientMetrics{ctrl: ctrl}
	mock.recorder = &MockClientMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientMetrics) EXPECT() *MockClientMetricsMockRecorder {
	return m.recorder
}

// RecordBlocked mocks base method.
func (m *MockClientMetrics) RecordBlocked(role string, d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordBlocked", role, d)
}

// RecordBlocked indicates an expected call of RecordBlocked.
func (mr *MockClientMetricsMockRecorder) RecordBlocked(role, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBlocked", reflect.TypeOf((*MockClientMetrics)(nil).RecordBlocked), role, d)
}

// RecordDegraded mocks base method.
func (m *MockClientMetrics) RecordDegraded(role, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDegraded", role, reason)
}

// RecordDegraded indicates an expected call of RecordDegraded.
func (mr *MockClientMetricsMockRecorder) RecordDegraded(role, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDegraded", reflect.TypeOf((*MockClientMetrics)(nil).RecordDegraded), role, reason)
}

// RecordReconnect mocks base method.
func (m *MockClientMetrics) RecordReconnect(role string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordReconnect", role)
}

// RecordReconnect indicates an expected call of RecordReconnect.
func (mr *MockClientMetricsMockRecorder) RecordReconnect(role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordReconnect", reflect.TypeOf((*MockClientMetrics)(nil).RecordReconnect), role)
}

// RecordTopologyRedeclare mocks base method.
func (m *MockClientMetrics) RecordTopologyRedeclare(role string, d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordTopologyRedeclare", role, d)
}

// RecordTopologyRedeclare indicates an expected call of RecordTopologyRedeclare.
func (mr *MockClientMetricsMockRecorder) RecordTopologyRedeclare(role, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTopologyRedeclare", reflect.TypeOf((*MockClientMetrics)(nil).RecordTopologyRedeclare), role, d)
}

// MockPublisherMetrics is a mock of PublisherMetrics interface.
type MockPublisherMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMetricsMockRecorder
	isgomock struct{}
}

// MockPublisherMetricsMockRecorder is the mock recorder for MockPublisherMetrics.
type MockPublisherMetricsMockRecorder struct {
	mock *MockPublisherMetrics
}

// NewMockPublisherMetrics creates a new mock instance.
func NewMockPublisherMetrics(ctrl *gomock.Controller) *MockPublisherMetrics {
	mock := &MockPublisherMetrics{ctrl: ctrl}
	mock.recorder = &MockPublisherMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisherMetrics) EXPECT() *MockPublisherMetricsMockRecorder {
	return m.recorder
}

// InFlightAdd mocks base method.
func (m *MockPublisherMetrics) InFlightAdd(exchange string, delta int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InFlightAdd", exchange, delta)
}

// InFlightAdd indicates an expected call of InFlightAdd.
func (mr *MockPublisherMetricsMockRecorder) InFlightAdd(exchange, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InFlightAdd", reflect.TypeOf((*MockPublisherMetrics)(nil).InFlightAdd), exchange, delta)
}

// RecordPublish mocks base method.
func (m *MockPublisherMetrics) RecordPublish(exchange, routingKey, messageType, outcome string, d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordPublish", exchange, routingKey, messageType, outcome, d)
}

// RecordPublish indicates an expected call of RecordPublish.
func (mr *MockPublisherMetricsMockRecorder) RecordPublish(exchange, routingKey, messageType, outcome, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPublish", reflect.TypeOf((*MockPublisherMetrics)(nil).RecordPublish), exchange, routingKey, messageType, outcome, d)
}

// RecordRetry mocks base method.
func (m *MockPublisherMetrics) RecordRetry(exchange, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRetry", exchange, reason)
}

// RecordRetry indicates an expected call of RecordRetry.
func (mr *MockPublisherMetricsMockRecorder) RecordRetry(exchange, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRetry", reflect.TypeOf((*MockPublisherMetrics)(nil).RecordRetry), exchange, reason)
}

// MockConsumerMetrics is a mock of ConsumerMetrics interface.
type MockConsumerMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerMetricsMockRecorder
	isgomock struct{}
}

// MockConsumerMetricsMockRecorder is the mock recorder for MockConsumerMetrics.
type MockConsumerMetricsMockRecorder struct {
	mock *MockConsumerMetrics
}

// NewMockConsumerMetrics creates a new mock instance.
func NewMockConsumerMetrics(ctrl *gomock.Controller) *MockConsumerMetrics {
	mock := &MockConsumerMetrics{ctrl: ctrl}
	mock.recorder = &MockConsumerMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerMetrics) EXPECT() *MockConsumerMetricsMockRecorder {
	return m.recorder
}

// RecordCancelled mocks base method.
func (m *MockConsumerMetrics) RecordCancelled(queue, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordCancelled", queue, reason)
}

// RecordCancelled indicates an expected call of RecordCancelled.
func (mr *MockConsumerMetricsMockRecorder) RecordCancelled(queue, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordCancelled", reflect.TypeOf((*MockConsumerMetrics)(nil).RecordCancelled), queue, reason)
}

// RecordHandler mocks base method.
func (m *MockConsumerMetrics) RecordHandler(queue, messageType, outcome string, d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordHandler", queue, messageType, outcome, d)
}

// RecordHandler indicates an expected call of RecordHandler.
func (mr *MockConsumerMetricsMockRecorder) RecordHandler(queue, messageType, outcome, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHandler", reflect.TypeOf((*MockConsumerMetrics)(nil).RecordHandler), queue, messageType, outcome, d)
}

// RecordHandlerAbortedChannelClosed mocks base method.
func (m *MockConsumerMetrics) RecordHandlerAbortedChannelClosed(queue string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordHandlerAbortedChannelClosed", queue)
}

// RecordHandlerAbortedChannelClosed indicates an expected call of RecordHandlerAbortedChannelClosed.
func (mr *MockConsumerMetricsMockRecorder) RecordHandlerAbortedChannelClosed(queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHandlerAbortedChannelClosed", reflect.TypeOf((*MockConsumerMetrics)(nil).RecordHandlerAbortedChannelClosed), queue)
}

// RecordHandlerTimeout mocks base method.
func (m *MockConsumerMetrics) RecordHandlerTimeout(queue string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordHandlerTimeout", queue)
}

// RecordHandlerTimeout indicates an expected call of RecordHandlerTimeout.
func (mr *MockConsumerMetricsMockRecorder) RecordHandlerTimeout(queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHandlerTimeout", reflect.TypeOf((*MockConsumerMetrics)(nil).RecordHandlerTimeout), queue)
}

// RecordMaxRedeliveries mocks base method.
func (m *MockConsumerMetrics) RecordMaxRedeliveries(queue, cause string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordMaxRedeliveries", queue, cause)
}

// RecordMaxRedeliveries indicates an expected call of RecordMaxRedeliveries.
func (mr *MockConsumerMetricsMockRecorder) RecordMaxRedeliveries(queue, cause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordMaxRedeliveries", reflect.TypeOf((*MockConsumerMetrics)(nil).RecordMaxRedeliveries), queue, cause)
}

// RecordReplierDropNoDLX mocks base method.
func (m *MockConsumerMetrics) RecordReplierDropNoDLX(queue string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordReplierDropNoDLX", queue)
}

// RecordReplierDropNoDLX indicates an expected call of RecordReplierDropNoDLX.
func (mr *MockConsumerMetricsMockRecorder) RecordReplierDropNoDLX(queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordReplierDropNoDLX", reflect.TypeOf((*MockConsumerMetrics)(nil).RecordReplierDropNoDLX), queue)
}

// RecordResubscribed mocks base method.
func (m *MockConsumerMetrics) RecordResubscribed(queue string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordResubscribed", queue)
}

// RecordResubscribed indicates an expected call of RecordResubscribed.
func (mr *MockConsumerMetricsMockRecorder) RecordResubscribed(queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordResubscribed", reflect.TypeOf((*MockConsumerMetrics)(nil).RecordResubscribed), queue)
}
