// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/brunomvsouza/warren/otel (interfaces: Tracer,Span,LinkingTracer)
//
// Generated by this command:
//
//	mockgen -destination tracer.go -package amqpmock github.com/brunomvsouza/warren/otel Tracer,Span,LinkingTracer
//

// Package amqpmock is a generated GoMock package.
package amqpmock

import (
	context "context"
	reflect "reflect"

	otel "github.com/brunomvsouza/warren/otel"
	attribute "go.opentelemetry.io/otel/attribute"
	codes "go.opentelemetry.io/otel/codes"
	gomock "go.uber.org/mock/gomock"
)

// MockTracer is a mock of Tracer interface.
type MockTracer struct {
	ctrl     *gomock.Controller
	recorder *MockTracerMockRecorder
	isgomock struct{}
}

// MockTracerMockRecorder is the mock recorder for MockTracer.
type MockTracerMockRecorder struct {
	mock *MockTracer
}

// NewMockTracer creates a new mock instance.
func NewMockTracer(ctrl *gomock.Controller) *MockTracer {
	mock := &MockTracer{ctrl: ctrl}
	mock.recorder = &MockTracerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracer) EXPECT() *MockTracerMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockTracer) Start(ctx context.Context, spanName string, attrs ...attribute.KeyValue) (context.Context, otel.Span) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spanName}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Start", varargs...)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(otel.Span)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockTracerMockRecorder) Start(ctx, spanName any, attrs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spanName}, attrs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTracer)(nil).Start), varargs...)
}

// MockSpan is a mock of Span interface.
type MockSpan struct {
	ctrl     *gomock.Controller
	recorder *MockSpanMockRecorder
	isgomock struct{}
}

// MockSpanMockRecorder is the mock recorder for MockSpan.
type MockSpanMockRecorder struct {
	mock *MockSpan
}

// NewMockSpan creates a new mock instance.
func NewMockSpan(ctrl *gomock.Controller) *MockSpan {
	mock := &MockSpan{ctrl: ctrl}
	mock.recorder = &MockSpanMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpan) EXPECT() *MockSpanMockRecorder {
	return m.recorder
}

// End mocks base method.
func (m *MockSpan) End() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "End")
}

// End indicates an expected call of End.
func (mr *MockSpanMockRecorder) End() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "End", reflect.TypeOf((*MockSpan)(nil).End))
}

// RecordError mocks base method.
func (m *MockSpan) RecordError(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordError", err)
}

// RecordError indicates an expected call of RecordError.
func (mr *MockSpanMockRecorder) RecordError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordError", reflect.TypeOf((*MockSpan)(nil).RecordError), err)
}

// SetAttributes mocks base method.
func (m *MockSpan) SetAttributes(attrs ...attribute.KeyValue) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SetAttributes", varargs...)
}

// SetAttributes indicates an expected call of SetAttributes.
func (mr *MockSpanMockRecorder) SetAttributes(attrs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAttributes", reflect.TypeOf((*MockSpan)(nil).SetAttributes), attrs...)
}

// SetStatus mocks base method.
func (m *MockSpan) SetStatus(code codes.Code, description string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", code, description)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockSpanMockRecorder) SetStatus(code, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockSpan)(nil).SetStatus), code, description)
}

// MockLinkingTracer is a mock of LinkingTracer interface.
type MockLinkingTracer struct {
	ctrl     *gomock.Controller
	recorder *MockLinkingTracerMockRecorder
	isgomock struct{}
}

// MockLinkingTracerMockRecorder is the mock recorder for MockLinkingTracer.
type MockLinkingTracerMockRecorder struct {
	mock *MockLinkingTracer
}

// NewMockLinkingTracer creates a new mock instance.
func NewMockLinkingTracer(ctrl *gomock.Controller) *MockLinkingTracer {
	mock := &MockLinkingTracer{ctrl: ctrl}
	mock.recorder = &MockLinkingTracerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkingTracer) EXPECT() *MockLinkingTracerMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockLinkingTracer) Start(ctx context.Context, spanName string, attrs ...attribute.KeyValue) (context.Context, otel.Span) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spanName}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Start", varargs...)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(otel.Span)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockLinkingTracerMockRecorder) Start(ctx, spanName any, attrs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spanName}, attrs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockLinkingTracer)(nil).Start), varargs...)
}

// StartWithLinks mocks base method.
func (m *MockLinkingTracer) StartWithLinks(ctx context.Context, spanName string, links []otel.Link, attrs ...attribute.KeyValue) (context.Context, otel.Span) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, spanName, links}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartWithLinks", varargs...)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(otel.Span)
	return ret0, ret1
}

// StartWithLinks indicates an expected call of StartWithLinks.
func (mr *MockLinkingTracerMockRecorder) StartWithLinks(ctx, spanName, links any, attrs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, spanName, links}, attrs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWithLinks", reflect.TypeOf((*MockLinkingTracer)(nil).StartWithLinks), varargs...)
}
