package codec

import (
	"fmt"

	"google.golang.org/protobuf/proto"
)

type protobufCodec struct{}

// NewProtobuf returns a codec that marshals and unmarshals Protocol Buffers
// messages using the canonical binary wire format.
//
// Both Encode and Decode require their value to implement proto.Message
// (the pointer type generated by protoc-gen-go); any other value yields
// ErrInvalidMessage. Decode unmarshals into the provided message, so callers
// must pass a non-nil pointer to a concrete proto message type.
func NewProtobuf() Codec {
	return &protobufCodec{}
}

func (c *protobufCodec) ContentType() string { return "application/x-protobuf" }

func (c *protobufCodec) Encode(v any) ([]byte, error) {
	m, ok := v.(proto.Message)
	if !ok {
		return nil, fmt.Errorf("%w: value of type %T does not implement proto.Message", ErrInvalidMessage, v)
	}
	out, err := proto.Marshal(m)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrInvalidMessage, err)
	}
	return out, nil
}

func (c *protobufCodec) Decode(data []byte, v any) error {
	m, ok := v.(proto.Message)
	if !ok {
		return fmt.Errorf("%w: value of type %T does not implement proto.Message", ErrInvalidMessage, v)
	}
	if err := proto.Unmarshal(data, m); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidMessage, err)
	}
	return nil
}

// ensure interface is satisfied at compile time.
var _ Codec = (*protobufCodec)(nil)
